services:
  # A Docker web service
  - type: web
    name: primeagent
    runtime: docker
    dockerfilePath: ./docker/render.Dockerfile
    repo: https://github.com/khulnasoft/primeagent
    branch: main
    plan: standard
    healthCheckPath: /health_check
    autoDeploy: false
    envVars:
      - key: PRIMEAGENT_DATABASE_URL
        value: sqlite:////app/data/.cache/primeagent/primeagent.db
      - key: PRIMEAGENT_HOST
        value: 0.0.0.0
      - key: PRIMEAGENT_PORT
        # default render port https://docs.render.com/web-services#port-binding
        value: 10000
      - key: PRIMEAGENT_LOG_LEVEL
        value: INFO
    disk:
      name: primeagent-data
      mountPath: /app/data
