apiVersion: v2
name: primeagent-ide
description: Helm chart for Primeagent IDE
type: application
version: 0.1.1
appVersion: latest
maintainers:
  - name: Primeagent
    email: support@khulnasoft.com
dependencies:
  - name: postgresql
    version: 15.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
