{{- $openshift := .Capabilities.APIVersions.Has "security.openshift.io/v1" -}}
{{- if .Values.serviceAccount.create -}}
{{- if $openshift -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "primeagent-runtime.fullname" . }}-openshift-scc
  labels:
    {{- include "primeagent-runtime.labels" . | nindent 4 }}
rules:
- apiGroups:
    - security.openshift.io
  resourceNames:
    - anyuid
    - nonroot-v2
  resources:
    - securitycontextconstraints
  verbs:
    - use
{{- end }}
{{- end -}}