version: "3.8"

services:
  primeagent:
    image: khulnasoft/primeagent:1.0-alpha
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - PRIMEAGENT_DATABASE_URL=postgresql://primeagent:primeagent@postgres:5432/primeagent
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - PRIMEAGENT_CONFIG_DIR=app/primeagent
    volumes:
      - primeagent-data:/app/primeagent

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: primeagent
      POSTGRES_PASSWORD: primeagent
      POSTGRES_DB: primeagent
    ports:
      - "5432:5432"
    volumes:
      - primeagent-postgres:/var/lib/postgresql/data

volumes:
  primeagent-postgres:
  primeagent-data:
