networks:
  dev-primeagent:

services:
  primeagent:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    image: dev-primeagent
    container_name: dev-primeagent
    restart: always
    ports:
      - "7860:7860"
      - "3000:3000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PRIMEAGENT_DATABASE_URL=postgresql://primeagent:primeagent@postgres:5432/primeagent
      - PRIMEAGENT_SUPERUSER=primeagent
      - PRIMEAGENT_SUPERUSER_PASSWORD=primeagent
      - PRIMEAGENT_CONFIG_DIR=/var/lib/primeagent
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - postgres
    networks:
      -  dev-primeagent


  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: primeagent
      POSTGRES_PASSWORD: primeagent
      POSTGRES_DB: primeagent
    ports:
      - "5432:5432"
    networks:
      -  dev-primeagent

